name: GET-BOT

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Getscreen.me Agent
      run: Invoke-WebRequest -Uri "https://getscreen.me/download/getscreen.exe" -OutFile "getscreen.exe"
    - run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - run: Set-DisplayResolution -Width 1280 -Height 720 -Force
    - name: Install Tibia
      run: Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/5q86a5etitmqzayx1jgkt/Unity-BOT.zip?rlkey=ybx3hdjmffz2zuj6f33yn5ol6&st=rskhaax4&dl=1" -OutFile "C:/TibiaBOT.zip"
    - run: Expand-Archive -Path "C:\TibiaBOT.zip" -DestinationPath "C:\Users\runneradmin\Desktop"
    - run: Expand-Archive -Path "C:\TibiaBOT.zip" -DestinationPath "C:\"
    - name: Install Getscreen.me Agent
      run: |
        .\getscreen.exe -install -register bjr.inside@gmail.com
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Expand-Archive ngrok.zip
    - run: .\ngrok\ngrok.exe authtoken "1wkarrs3XJpaLWvElRLbGKecYlW_2VL7Z7TFQguFU6CC5xWdP"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\getscreen.exe -start
    - run: .\ngrok\ngrok.exe tcp 3389
