name: GET-BOT

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Getscreen.me Agent
      run: Invoke-WebRequest -Uri "https://getscreen.me/download/getscreen.exe" -OutFile "getscreen.exe"
    - name: Install Getscreen.me Agent
      run: |
        .\getscreen.exe /silent /email bjr.inside@gmail.com
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "glwahta57q" -Force)
